job: analysis # can be experiment, analysis or test (relevant for picking the experiment folder)

language: de

ckpt_asr: logs/ensemble/train/binary/b15/DAT/version_3
ckpt_ac:
  b3: logs/ac/train/binary/b3/version_1/checkpoints/last.ckpt
  b7: logs/ensemble/train/binary/b7/DAT/version_2/checkpoints/last.ckpt
  b11: logs/ensemble/train/binary/b11/DAT/version_2/checkpoints/last.ckpt
  b15: logs/ensemble/train/binary/b15/DAT/version_3/checkpoints/last.ckpt

asr_file: config/asr/conformert.yaml
ac_file: config/ac/binary.yaml
data_file: config/data/default.yaml
trainer_file: config/trainer/default.yaml

# ENSEMBLE: required to initialize the experiment and create the data files
ensemble:
  branch: 7
  ac_weight: 1
  asr_weight: 1
  mode: DAT
  action: train

components:
  GradChecker:
    branches: [15]
    ac_weights: [100]
    asr_weights: [1]
    trained_asr: [false]
    trained_ac: [false]

  EncoderViz:
    tsne:
      learning_rate: auto
      init: pca
    n_samples: 100 # num. of samples per dataset

  MAPSSWE:
    path_a: logs/de/asr/evaluate/version_48/results.json
    path_b: logs/de/asr/evaluate/version_43/results.json

  ErrorCounter:
    path: logs/de/asr/evaluate/version_48/results.json
